WomenWhoCode/WWCodeMobile

coding-projects/android/README.md
coding-projects/ios/README.md

addresses issue #61 
- Updates project-level README files using template
- Adds details to Contribution Guidelines section
- Adds maintainer names and profiles
- Adds basic intro with project type and tech stack
- Outlines TODOs that still need to be completed (GitHub issues have been created for these TODOs)

creates READMEs for android and ios projects using template.

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

**Implements issue #120** 
Created `DaysView` in the `SettingsView` file which includes adding a text called `Show Days` and the days of the week similar to the screenshot provided in the issue.
| Light Mode | Dark Mode | 
| --- | --- |
| ![simulator_screenshot_B8E610F9-1335-4A5F-86D4-F20AB31FDD66](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/a4dc7e37-a7be-460a-aecc-7b0315b90f44) | ![simulator_screenshot_51D8DA63-595D-4D24-A78E-567BAB19D45C](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/8ff8d3d5-6509-441e-8a82-725266576805) |
No unit tests as this is mainly UI and not logic. You can wire up the app to present the SettingsView, which will display the Days View.

Add show days text in settings [Issue 120]

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

##Link the issue # to this PR
Implements issue #104 
This PR adds a navigation title to the `SettingsView` file

ios issue #104-add navigation title to settings view

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implements issue #116 
This PR adds an app theme row to the settings view

ios-issue-116_feature/add app theme row to settings view

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Fixed build fail in tracker app due to redeclaration of DaysView caused while merging conflicts. Sorry!

[iOS] Fix build fail in tracker app

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

* Adds Section Header for Info and Feedback with the sfsymbol
Screenshot:

[iOS] [Issue #105] Add Section Header Info and Feedback

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implements issue #106. 
@clc80 and @devanshimodha My PR is ready for review! 
I updated SettingsView to add Notifications section header.

added section header for notifications

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

#112 Added a Rate App row to Setting Screen
Following a similar structure to the contributions before, added a rate app row with a start icon and a chevron.

Added a Rate App row to Settings screen

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implemented the Add About us Row in Info and Feedback Section #109
Screenshot:

[iOS] [#109] Add About us row in settings

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implemented #114 Added a version number row to the settings.

[iOS] [#114] - Add version row

---

coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift

Implements issue #127 
This PR links the plus button on the `List Screen` to the `Details/Add/Edit screen`
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/0d31a179-ddbf-48b8-9772-cf1068012c58

feature/ios-issue-127_link-plus-button-to details-screen

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/theme/Color.kt
coding-projects/android/TaskTracker/app/src/main/res/drawable/baseline_cancel_24.xml
coding-projects/android/TaskTracker/app/src/main/res/drawable/outline_delete_24.xml
coding-projects/android/TaskTracker/app/src/main/res/values/dimens.xml
coding-projects/android/TaskTracker/app/src/main/res/values/strings.xml

Issue https://github.com/WomenWhoCode/WWCodeMobile/issues/88
Added Compose UI for Detail Screen:  
-  added Date, Start time, and End time text
-  added textbox for activity description
-  added button that displays date
- added button that displays start time
- added button that displays end time
- added delete button
- added cancel button
- added done button
Changes in files:
- TaskDetailScreen.kt (added compose UI for Detail Screen)
- Color.kt (added green color for buttons)
- added 2 new drawables for image buttons (delete and cancel)
- strings.xml (added string resources)
- -dimens.xml (added dimensions)
Test:
At this moment only in design mode in Android studio, screenshot is attached to PR

Android - UI - Detail Screen: Scaffold initial screen with elements#88

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

https://github.com/WomenWhoCode/WWCodeMobile/issues/133
@clc80 @devanshimodha Please review
I added logic to dismiss the details screen on done button tap to go to the list view.
https://github.com/WomenWhoCode/WWCodeMobile/assets/22762162/73123211-77d8-440e-9306-3cf5b7171974

[iOS][133] Done button redirect

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

**Implements issue #130** 
Added DatePicker in compact style to display picker for start time and end time. Also created reusable `TextView` to ensure that the text for "Date", "Start Time" and "End Time" are consistent
| Light Mode | Dark Mode | 
| --- | --- |
| ![simulator_screenshot_51902438-684F-4669-9B6F-11EE1430B5C7](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/cfd49eb1-a08c-4c3b-93a1-65214a2d6dee) | ![simulator_screenshot_7227B384-C178-49C6-B003-D177CD1F5FAE](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/de8987c8-7760-4dcb-8c01-0a475d7221a1) |

[iOS] [Issue 130] Add time picker

---

pull_request_template.md

Implements issue #211 
This PR provides guidance on the PR template for naming the PR title and also the branch title
Can I get a review @clc80 and @ceceliacreates when you get a chance please?

Issue #211 Update PR Template to Add Guidance on PR Title

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

iOS Issue #118 
- Create  `ReminderNotificationView`   in `SettingsView` 
- Add a text and toggle

[iOS] Issue #118  Add Task Reminder row to Settings

---

coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift

Implements issue #227 
This PR:
-  passes the task model form the ListView to the DetailsView
- embeds the ListView in a NavigationStack
- populates the DetailsView with task data passed from the ListView.
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/85127973-0dae-4d6d-9a3b-86afd029e2a2

[iOS]  issue #227 Pass task from list screen to details screen

---

coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift

#231
- Add Settings icon on top right of the list screen
- Link SettingsView on icon tap

#231 add settings icon

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskSettings/TaskSettingsScreen.kt

[#169
](https://github.com/WomenWhoCode/WWCodeMobile/issues/169)
**Description**
Adding text footer to show current app version
**Result**

[Android] Issue #169 Add version footer in settings

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

Issue Link
Implements issue #235 
Description
This PR:
-  fixes the edit task bug, by editing current task instead of creating a new task when the done button is pressed.
- removes @Query task in DetailsView not needed
- removes duplicate name (`selectedDate`) for `taskDate` on DetailsView
Video
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/c5ddb9ea-2058-4b4e-bbf6-e79f626b906d

[iOS] Issue #235 Editing List Item Creates New List Item Instead

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implements issue #111 
This PR adds a tutorial row to the settings view

[iOS] Issue #111  Add tutorial row to the settings view

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt

* closes issue  #250
* Changed the TextField to an OutlinedTextField
* Removed the colors being assigned on the text field
* Removed the border being assigned in the modifier
* Swapped out the label text for a placeholder text

Changed Textfield to OutlinedTextField in TaskDetailScreen

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

[#122] Added version number footer 
Also removed some spacing issue below Notifications header.

[iOS][#122] Add version number footer 

---

coding-projects/ios/TaskTracker/TaskTracker.xcodeproj/project.pbxproj
coding-projects/ios/TaskTracker/TaskTracker/Common/DeleteConfirmationPopupView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift

- Add  modifier `onDelete`
- Add new method `deleteTask` to handle deletion
- Create `DeleteConfirmationPopupView` common view
- Reuse `DeleteConfirmationPopupView ` in `ListView`and `DetailScreen`
- Add Pragma Marks and new comments in `ListView`
- Swipe deletion
- Confirmation popup when click delete

[IOS] Issue #239 Add delete swiper for task

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskList/TaskListViewModel.kt

Implementation for #281 
Added sort by descending referencing TimeUtil.convertDateToMillis in the getAllTasks function of the TaskListViewModel file.
Test
Create tasks somewhat random throughout the year and see how they show up - the order should always be in DESC order.

Android - Bug -  Added sort by DESC to the List screen task order

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsViewModel.swift

Implements issue #226
This PR fixes a bug where the textfield is squished when the keyboard is visible, by observing the keyboard's  height.
It also includes a focus mode on the textfield to help dismiss the keyboard if the user taps outside the keyboard.
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/107bb777-310b-4768-adb1-86f11f93adb9

[iOS] Issue-266 Fix squished textfield on details view screen
