PragmaticProgrammerCH4-notes.md

Pragmatic Programmer Ch4 notes @navatijain hi

Add files via upload CH4 Pragmatic Programmer

---

Resources/iOSDev.md

Links were not hyperlinked due to incorrect formatting

Fix link formatting

---

coding-projects/README.md
coding-projects/android/README.md
coding-projects/ios/README.md
coding-projects/resources/project-readme-template.md

This fixes issue #58 by updating the template README file for the coding-projects repo.

Issue 58-Update Coding Projects Readme

---

coding-projects/ios/TaskTracker/.gitignore
coding-projects/ios/TaskTracker/TaskTracker.xcodeproj/project.pbxproj
coding-projects/ios/TaskTracker/TaskTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
coding-projects/ios/TaskTracker/TaskTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
coding-projects/ios/TaskTracker/TaskTracker/Assets.xcassets/AccentColor.colorset/Contents.json
coding-projects/ios/TaskTracker/TaskTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
coding-projects/ios/TaskTracker/TaskTracker/Assets.xcassets/Contents.json
coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsModel.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsViewModel.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListModel.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListViewModel.swift
coding-projects/ios/TaskTracker/TaskTracker/Preview Content/Preview Assets.xcassets/Contents.json
coding-projects/ios/TaskTracker/TaskTracker/TaskTrackerApp.swift

Addresses issue [https://github.com/WomenWhoCode/WWCodeMobile/issues/68](https://github.com/WomenWhoCode/WWCodeMobile/issues/68)
- Created a new iOS project
- Created two groups one for the "Details Screen" and one for the "List Screen"
- Each group contains empty Model, View, and Model View  files

Created iOS initial structure

---

templates/pull_request_template.md

Implements issue: https://github.com/WomenWhoCode/WWCodeMobile/issues/140

Create a PR Template for use in Android and iOS Group Projects

---

coding-projects/android/Hello World!

Add description about Rohit Jakhar(My self)

Update Hello World!

---

coding-projects/android/Hello World!

Implements issue #100 
@renweview @gaurigadkari  My Hello World PR is ready for review
Added a line to the Hello World File to introduce myself.

Updated Hello World by Su

---

coding-projects/android/Hello World!

Implements issue #100
Added a line to the Hello World File to introduce myself.

Android [Issue 100] Update Hello World

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

* Implements issue #107 - Add "What's New" section header

Issue #107: iOS - UI - Beginner - Add a Section Header to the SettingsView titled What's New

---

coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListModel.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListViewModel.swift

**Implements issue #125** 
Created `ActivityView` to hold the mock data to populate the list items and created `ActivityItemView` to display the activity name and duration for each item in the list.
| Light Mode | Dark Mode | 
| --- | --- |
| ![simulator_screenshot_607E1356-C32C-4E06-B548-52632BB9E189](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/d8283a9f-077c-4641-953d-13f29990c9a4) | ![simulator_screenshot_9B25A277-5284-46DA-88E2-F9028401409C](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/8cf72cad-158c-4521-9bf1-4f7a0842cca4) |

[iOS] [Issue 125] Add list items

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Implements issue #119 
@devanshimodha @clc80 My PR is ready for review!
I added a row to toggle badge in the SettingsView.

added row to toggle badge

---

coding-projects/README.md

Closes #135 
@ceceliacreates, My PR is ready for review! :)  
This PR adds information about how users should interact with the to do list app. This helps contributors gain a better understanding of how to work on this project. 
Click on the Markdown preview in VSCode to view the section in Markdown.

[docs]: add usage section in README

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsViewModel.swift

- Implements issue #128 - Scaffold initial screen with elements
- Add comments for related task
Review Request: @clc80 @devanshimodha

Issue #128: iOS - UI - Detail Screen: Scaffold initial screen with elements

---

coding-projects/ios/README.md

Added useful links for the setup:
- Xcode documentation
- Xcode Source Control Management
- Combining code changes in a source control repository

#161 update Setup and Configuration

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

https://github.com/WomenWhoCode/WWCodeMobile/issues/110
@clc80 @devanshimodha pls review!

[iOS][110] Add privacy row to setting view

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

#129 : Added a date picker to match as time picker UI. Also did refactor to remove unneeded code.
https://github.com/WomenWhoCode/WWCodeMobile/assets/13859276/e53b9237-e3c1-436e-a948-3c407ab03f23

[iOS][#129] Added date picker and code refactor

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/res/values/strings.xml

TODO: Link the issue #91 
TODO: Request a maintainer to review your PR
* @baghaii , @gaurigadkari , @renweview  Kindly review my PR
TODO: Write a brief description of what your PR accomplished
* Added confirmation popup for cancel.
* Go to TaskDetailScreen->Press on cancel button

Android Issue #91: Added confirmation popup for cancel button.

---

issue_template.md

Implements issue #212 
This PR creates an issue template to help folks write better issues.
Can I get a review @clc80 and @ceceliacreates when you get a chance please?

Issue #212 Create Issue Template To Provide Guidance on Writing Issues

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

https://github.com/WomenWhoCode/WWCodeMobile/issues/108
@clc80 @devanshimodha Please review
Added header to appearance section.

[iOS] 108: Add appearance section header

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

Implements issue #80 
This PR implements deleting timed activity logic using SwiftData.
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/31094bb6-3cb9-43e6-b88b-15506ff84177

[iOS] Issue #80 Delete timed activity

---

coding-projects/ios/TaskTracker/TaskTracker/ContentView.swift
coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift

#134 - Only show delete icon when editing item
https://github.com/WomenWhoCode/WWCodeMobile/assets/13859276/ba75a01e-a8a4-494d-a5a0-bf815fbcc7ff

[iOS] 134 - Only show delete icon when editing item

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/MainScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt

* Closes issue #0093
*  @gaurigadkari @baghaii @renweview my PR is ready for review!
* How did your PR fix the issue mentioned above? What files were changed or created? What did your changes do?
* The done button now redirects users from the Detail Screen to the List Screen.  The TaskDetailcreen.kt
https://github.com/WomenWhoCode/WWCodeMobile/assets/96094922/73d1a78d-32b7-42ee-8f6b-0e924209e15f
* Tap on the 'Done' button in the Task Detail Screen to see that it redirects to the List Screen.

Android Issue #0093 Done button redirect on Detail Screen

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskSettings/TaskSettingsScreen.kt
coding-projects/android/TaskTracker/app/src/main/res/values/strings.xml

#174 
@baghaii @gaurigadkari @renweview kindly review.
Added Task reminder row in TaskSetting Screen
Preview :

Android issue #174 : Add Task Reminder Row

---

coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListView.swift
coding-projects/ios/TaskTracker/TaskTracker/List Screen/ListViewModel.swift

[#190] - Integration - Add Time Activity
Sorted the activity to match wireframe and removed unneeded code.

[iOS][#190] - Integration - Add Time Activity

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskSettings/TaskSettingsScreen.kt

Fill out the sections of this PR template that applies.
If your PR is documentation-based or is very short, you may skip the parts after requesting a reviewer
* Android Issue #261 Fix settings page
closes issue #261 
@gaurigadkari or @renweview can you please review this?
The sp import and a parenthesis were missing. This PR books them back.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
</td>
<td>
</td>
</tr>
</table>
This PR fixes issue #261 
Go to the TaskSettingsScreen. 
Make sure it works

Android - 261 - Some minor merge issues on TaskSettingsScreen

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/TimeUtil.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/res/values/strings.xml

closes issue https://github.com/WomenWhoCode/WWCodeMobile/issues/90
@renweview, @gaurigadkari, @baghaii my PR is ready for initial review.
Added timepicker for start time and end time 
Goto TaskDetailScreen ->press Start Time-> show time picker appear. Same for End Time

Android - Issue 90 - Added time picker

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/MainScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/navigation/NavScreens.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailViewModel.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskList/TaskItemView.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskList/TaskListScreen.kt

https://github.com/WomenWhoCode/WWCodeMobile/assets/79568910/5ae607c7-831a-44ee-91c1-1a8da4ef936a
Closes #94 
Changed files:
MainScreen - Task id passed in nav route
TaskDetailScreen - Delete button hidden while adding task and shown while editing task
TaskDetailViewModel - Logic for show and hide delete button
TaskItemView - Click for TaskCard
TaskListScreen -  Navigate to Detail with argument

android issue #94 shown delete icon only when editing on detail screen

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/TimeUtil.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/data/ITaskRepository.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/data/TaskDao.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/data/TaskRepository.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/data/model/Task.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailViewModel.kt

closes issue #77 and #187 
@baghaii, @renweview , @gaurigadkari My PR is ready for review !!
Files changed:
TaskDetailScreen, TaskDetailViewModel,Task - logic for update
when testing this PR, please uncomment following:

Android Issue #77 edit timed activity (update logic)

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskList/TaskListViewModel.kt

* closes issue #0185 
* @baghaii @renweview @gaurigadkari My PR is ready for review! 
* How did your PR fix the issue mentioned above? What files were changed or created? What did your changes do?
* The TaskListViewModel has been updated to take in the flow that gets all the tasks from the repository and displays them on the TaskList Screen.  TaskListViewModel.kt was changed
https://github.com/WomenWhoCode/WWCodeMobile/assets/96094922/6cf3f7c7-cdbc-4a27-9e33-d82257604252
* Add a new task in detail screen,  and see tasklist screen update accordingly.

Android Issue #0185 - Integration - Display Timed Activities on TaskList Screen

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/res/values/strings.xml

closes issue https://github.com/WomenWhoCode/WWCodeMobile/issues/92
@baghaii, @renweview , @gaurigadkari My PR is ready for review
Added delete popup
Chose task from task list, press delete button -> Delete popup will appear

Android - issue 92  - Added confirmation popup for delete button

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt

closes issue #79  
@baghaii @renweview @gaurigadkari My PR is ready for review!
Added deleting existing task
Select task -> Press on delete button-> Deletion popup appears-> Press Ok-> Task should be deleted

Android - Issue 79 - Detail deleting task

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskList/TaskItemView.kt

Added AcitivityName to be limited to 1 line in the UI

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

[iOS] #117 Added app icon row

---

coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/TimeUtil.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailScreen.kt
coding-projects/android/TaskTracker/app/src/main/java/com/example/tasktracker/ui/TaskDetail/TaskDetailViewModel.kt

* closes issue #0271
* @baghaii  My PR is ready for review! 
* How did your PR fix the issue mentioned above? What files were changed or created? What did your changes do?
* remove the line in TimeUtil.kt that is setting the time zone to UTC so that the date is correct when adding a new task.
* For example, what unit tests need to be run, if any? What buttons do you need to tap on which screens to test the app flow?
* add new task in detail screen to see the date is set correctly

Android Issue #0271 Bug - Fix Date for New Tasks on Detail Screen

---

coding-projects/ios/TaskTracker/TaskTracker/Details Screen/DetailsView.swift

Fixed the segment selection by moving onTapGesture and handling isTextFieldFocused to dismiss keyboard which allows segment selection
https://github.com/WomenWhoCode/WWCodeMobile/assets/32483283/6b7bdd6a-e9d1-4a43-bc0a-ef7b00a635cc

#291 fix priority segment selection

---

coding-projects/ios/TaskTracker/TaskTracker/Settings/SettingsView.swift

Aligning structs and adding parentheses fixed the build issue

#289 fix alignment and parentheses
